name: frontend CD

permissions:
  contents: read

on:
  push:
    branches: [main]

jobs:
  deploy_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: EC2 Front Docker Run
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.FRONT_EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.FRONT_EC2_PEM_KEY }}
          script: |
            docker stop ${{ secrets.FRONT_DOCKER_CONTAINER }} || true
            docker rm ${{ secrets.FRONT_DOCKER_CONTAINER }} || true
            docker pull ${{ secrets.FRONT_DOCKER_IMAGE }}:latest
            docker run --name ${{ secrets.FRONT_DOCKER_CONTAINER }} --rm -d -p 3000:3000 \
              -e NODE_ENV=production \
              -e NEXT_PUBLIC_FRONT_ENV_MODE=production \
              ${{ secrets.FRONT_DOCKER_IMAGE }}:latest

      - name: Remove dangling images
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.FRONT_EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.FRONT_EC2_PEM_KEY }}
          script: |
            docker images -q --filter "dangling=true" | xargs docker rmi -f
            docker image prune -f
